# Generated by Django 3.2.9 on 2021-12-03 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airpollution', '0003_auto_20211203_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollutantentry',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='airpollution.country'),
            preserve_default=False,
        ),
    ]
